---
title: "C-STAR"
output:
  distill::distill_article:
    self_contained: false
    anchor_sections: FALSE
    css: [theme_inferno_black.css]
site: distill::distill_website
#favicon: transparency.svg
---

```{r, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```
      
The [Center for the Study of Antimicrobial Resistance (C-STAR)](https://cstar.med.upenn.edu/) brings together experts from across the University of Pennsylvania to create new solutions to the public health threat posed by antimicrobial resistance (AR). The Center includes three primary areas of research focus: (1)  Translational, (2) Global, and (3) Community. The [motion laboratory](https://motionlab.site), directed by Brendan J. Kelly, MD, MS, is proud to serve as the core laboratory for the Translational AR focus.  
  
C-STAR collaborators are encouraged to utilize the motion lab biorepository to address new research questions and validate findings from pilot studies. Our biorepository (as of `r format(as.Date(system('git log -1 --format="%ad" --date=iso -- data_cstar/p_cstar_lv_raw_specimen_totals.html', intern = TRUE)), '%d %B %Y')`) includes:  
  
  
#### Biospecimens Obtained from Human Subjects at High Risk for Antimicrobial Resistant Infections  
  
<iframe src="data_cstar/p_cstar_lv_raw_specimen_totals.html" width=900 height=500 style="border: 0; box-shadow: 5px 5px 56px 0px rgba(0,0,0,0.25);" class="l-body-outset"></iframe>  

<br>  


#### Microbial DNA Extracted from Human Biospecimens  
  
<iframe src="data_cstar/p_cstar_lv_dna_specimen_totals.html" width=900 height=500 style="border: 0; box-shadow: 5px 5px 56px 0px rgba(0,0,0,0.25);" class="l-body-outset"></iframe>  

<br>  


#### Cultured Bacterial Strains with Phenotypic Antimicrobial Resistance  
  
<iframe src="data_cstar/p_cstar_lv_cx_totals.html" width=800 height=600 style="border: 0; box-shadow: 5px 5px 56px 0px rgba(0,0,0,0.25);" class="l-page"></iframe>  




 <br>

 <br>

 <br>

  