---
title: "Team"
output:
  distill::distill_article:
    self_contained: false
    anchor_sections: FALSE
    css: [theme_inferno_black.css]
site: distill::distill_website
favicon: microscope_white.png
---

```{r, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE, fig.align='center', out.width='90%', fig.retina=2}

knitr::opts_chunk$set(echo = FALSE)

```

### Lab Members  

```{r members, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

#' #################################
#' load libraries and set seed
#' #################################
library(tidyverse)
library(glue)
library(gt)
library(gtExtras)


#' #####################################
#' read bio data
#' #####################################
read_csv("people/MOTIONPeopleWithSurv_DATA.csv") |> 
  identity() -> motion_people

read_csv("people/motion_people_roles.csv") |> 
  identity() -> people_roles


#' #####################################
#' convert headshots to webp format (size compression)
#' #####################################
system("cd ~/motionlab-site/people/headshots; bash convert_to_webp.sh")


#' #####################################
#' concatenate bio data to paragraph and read photos
#' #####################################
motion_people |> 
  left_join(people_roles, by = c("your_first_name", "your_last_name")) |> 
  mutate(your_pronouns = gsub(pattern = "\\(|\\)", replacement = "", x = your_pronouns)) |> 
  mutate(your_pronouns = tolower(your_pronouns)) |> 
  mutate(your_middle_initial = ifelse(is.na(your_middle_initial), NA, paste0(gsub("\\.","",your_middle_initial),"."))) |> 
  mutate(your_website = ifelse(is.na(your_website), NA, glue("Additional information can be found <a href='{your_website}'>here</a>."))) |> 
  mutate(biography = glue("<b>{your_first_name} {your_middle_initial} {your_last_name}, {your_credentials}</b> ({your_pronouns}) is {your_title} at the University of Pennsylvania. {your_work_background} {your_focus} {your_interests} {your_website}", .na = "")) |>
  mutate(headshot_path = paste0("./people/headshots/",your_photo)) |> 
  mutate(headshot_path_webp = gsub(pattern = "jpg|jpeg|png|PNG|jpeg|JPG","webp",headshot_path)) |> 
  select(headshot_path, headshot_path_webp, biography, role, your_last_name) |> 
  identity() -> motion_bios

motion_bios |> 
  arrange(desc(role), your_last_name) |> 
  filter(role %in% c("pi", "member")) |> 
  select(headshot_path_webp, biography) |> 
  distinct() |> 
  gt() |> 
  #gt::cols_label(headshot_path_webp = "", biography = "") |> 
  gt::tab_options(column_labels.hidden = TRUE) |> 
  gt::cols_align(align = "center", columns = headshot_path_webp) |> 
  gt::cols_align(align = "left", columns = biography) |> 
  gt::fmt_markdown(biography) |> 
  gt::cols_width(headshot_path_webp ~ px(300)) |> 
  gtExtras::gt_img_rows(columns = headshot_path_webp, img_source = "local", height = 200) |> 
  #gtExtras::gt_theme_538()
  gtExtras::gt_theme_guardian() |> 
  gt::opt_table_outline(style = "solid", width = px(3), color = "#FFFFFF") |> 
  identity() -> members

members |> 
  gtsave("people/members.html", inline_css = TRUE)

# ````{=html}
# ```{r, echo=FALSE, results='asis'}
# xfun::file_string('people/members.html')
# ```
# ````

```


::: {#members}

```{r, echo=FALSE, results='asis'}

#htmltools::includeHTML('people/members.html')

members |> 
  as_raw_html(inline_css = TRUE)

```

:::


### Lab Partners  

```{r partners, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

motion_bios |> 
  arrange(desc(role), your_last_name) |> 
  filter(role %in% c("partner")) |> 
  select(headshot_path_webp, biography) |> 
  distinct() |> 
  gt() |> 
  #gt::cols_label(headshot_path_webp = "", biography = "") |> 
  gt::tab_options(column_labels.hidden = TRUE) |> 
  gt::cols_align(align = "center", columns = headshot_path_webp) |> 
  gt::cols_align(align = "left", columns = biography) |> 
  gt::fmt_markdown(biography) |> 
  gt::cols_width(headshot_path_webp ~ px(300)) |> 
  gtExtras::gt_img_rows(columns = headshot_path_webp, img_source = "local", height = 200) |> 
  #gtExtras::gt_theme_538()
  gtExtras::gt_theme_guardian() |> 
  gt::opt_table_outline(style = "solid", width = px(3), color = "#FFFFFF") |> 
  identity() -> partners

partners |> 
  gtsave("people/members.html", inline_css = TRUE)


```

::: {#partners}

```{r, echo=FALSE, results='asis'}

#htmltools::includeHTML('people/partners.html')

partners |> 
  as_raw_html(inline_css = TRUE)

```

:::


