---
title: "Getting Started in the Lab"
output:
  distill::distill_article:
    self_contained: false
    anchor_sections: FALSE
    css: [theme_inferno_black.css]
site: distill::distill_website
favicon: microscope_white.png
---

```{r, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```
  
### Checklist for New Lab Members      

```{r onboarding_checklist, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE, layout="l-body-outset", fig.width=6}

#' #################################
#' load libraries and set seed
#' #################################
library(tidyverse)
library(gt)
library(gtExtras)


#' #################################
#'  read and format meeting data
#' #################################

read_csv(file = "https://docs.google.com/spreadsheets/d/1AL72L7NQku5Y2iUGK84H0Y0NszRowPL_OmXjyzFaW4c/export?format=csv") %>%
  identity() -> motion_onboarding
#motion_onboarding

motion_onboarding |> 
  mutate(links = stringr::str_extract_all(string = Task, pattern = "(^|\\s)http(.*?)($|\\s)")) |> 
  mutate(links = map(.x = links, .f = ~ stringr::str_trim(string = .x, side = "both"))) |>
  mutate(links_count = map_dbl(links, length)) |>  
  mutate(links_md = map(.x = links, .f = ~ paste0("[",.x,"](",.x,")"))) |>
  rowwise() |> 
  mutate(Task = ifelse(links_count == 0, Task, map_chr(.x = links, .y = links_md, .f = ~ stringr::str_replace_all(string = Task, pattern = .x, replacement = .y)))) |> 
  ungroup() |> 
  mutate(Task = map(Task, gt::md)) |> 
  select(Step, Task, Notes) |> 
  identity() -> motion_onboarding_md

motion_onboarding_md |> 
  write_csv("equipment/motion_onboarding.csv")

motion_onboarding_md |> 
  gt() |> 
  gt::sub_missing() |> 
  gt::fmt_markdown(Task) |> 
  gtExtras::gt_theme_538() |> 
  gt::data_color(
    columns = Step,
    method = "numeric",
    palette = viridis::mako(n = n_distinct(motion_onboarding$Step), alpha = 1),
    domain = NULL,
    reverse = TRUE
  )





```
  
 <br>

 <br>

 <br>

  