---
title: "Orders & Inventory"
output:
  distill::distill_article:
    self_contained: false
    anchor_sections: FALSE
    css: [theme_inferno_black.css]
site: distill::distill_website
#favicon: transparency.svg
---

```{r, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(gt)
library(gtExtras)
library(knitr)

```
  
### Orders      

```{r}

order_dat <- read_csv("order_data/order_update.csv.gz")

order_dat |> 
  rename(product = product_description) |> 
  gt() |> 
  gtExtras::gt_theme_538() |> 
  gt::sub_missing() |> 
  gt::opt_interactive(
    use_filters = TRUE,
    use_compact_mode = TRUE,
    use_text_wrapping = TRUE
  )

```


### Inventory      

#### Supplies  

```{r}

inventory_dat <- read_csv("order_data/inventory_update.csv.gz")

inventory_dat |> 
  rename(product = product_description) |> 
  gt() |> 
  gtExtras::gt_theme_538() |> 
  gt::sub_missing() |> 
  gt::opt_interactive(
    use_filters = TRUE,
    use_compact_mode = TRUE,
    use_text_wrapping = TRUE
  )

```


#### Equipment  

```{r}

equipment_dat <- read_csv("order_data/equipment_update.csv.gz")

equipment_dat |> 
  #rename(product = product_description) |> 
  gt() |> 
  gtExtras::gt_theme_538() |> 
  gt::sub_missing() |> 
  # gt::opt_interactive(
  #   use_filters = TRUE,
  #   use_compact_mode = TRUE,
  #   use_text_wrapping = TRUE
  # ) |> 
  identity()

```


<br>

<br>

<br>

  