---
title: "Pre-Prints"
output:
  distill::distill_article:
    self_contained: false
    anchor_sections: FALSE
    css: [theme_inferno_black.css]
site: distill::distill_website
favicon: microscope_white.png
---

```{r, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE, fig.align='center', out.width='90%', fig.retina=2}

knitr::opts_chunk$set(echo = FALSE)

```

```{r preprints, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE, layout="l-body-outset", fig.width=6}

#' #################################
#' load libraries and set seed
#' #################################
library(tidyverse)
library(gt)
library(gtExtras)


#' #####################################
#' read DOIs with bibtex
#' #####################################

doi_tib <- read_rds("pubs/doi.rds")


#' #####################################
#' put bibtex in tabular form & join with links
#' #####################################

doi_tib |> 
  # filter out missing bibtex
  filter(grepl("not found", tolower(bib)) == FALSE) |>   
  # format data for presentation
  mutate(year = stringr::str_match(string = bib, pattern = "year\\=\\{\\s*(.*?)\\s*\\}")[,2]) |> 
  mutate(authors = stringr::str_match(string = bib, pattern = "author\\=\\{\\s*(.*?)\\s*\\}")[,2]) |> 
  mutate(title = stringr::str_match(string = bib, pattern = "title\\=\\{\\s*(.*?)\\s*\\}")[,2]) |> 
  mutate(journal = stringr::str_match(string = bib, pattern = "journal\\=\\{\\s*(.*?)\\s*\\}")[,2]) |> 
  mutate(journal = replace(journal, is.na(journal), "preprint")) |> 
  mutate(publisher = stringr::str_match(string = bib, pattern = "publisher\\=\\{\\s*(.*?)\\s*\\}")[,2]) |> 
  mutate(url = stringr::str_match(string = bib, pattern = "year\\=\\{\\s*(.*?)\\s*\\}")[,2]) |> 
  mutate(journal = gsub("&amp;", "&", journal)) |> 
  arrange(desc(year), title) |> 
  rename_all(.funs = ~ stringr::str_to_title(.x)) |> 
  rename("DOI" = "Doi") |> 
  # add html links
  mutate(DOI = map(.x = DOI, .f = ~ htmltools::a(href = paste0("https://doi.org/", .x), .x)),
        DOI = map(.x = DOI, .f = ~ gt::html(as.character(.x)))) |> 
  identity() -> bib_tib

bib_tib |> 
  # focus on preprints
  filter(Journal == "preprint") |> 
  # check order
  arrange(desc(Year), Title) |> 
  select(Year, Authors, Title, Journal, DOI) |> 
  gt() |> 
  gt::sub_missing() |> 
  gtExtras::gt_theme_538()


```





 <br>

 <br>

 <br>
 
  
  

