---
title: "Protocols"
output:
  distill::distill_article:
    self_contained: false
    anchor_sections: FALSE
    css: [theme_inferno_black.css]
site: distill::distill_website
favicon: microscope_white.png
---

```{r, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(gt)
library(gtExtras)
library(knitr)


```
  
### Download Protocols    

```{r}

protocol_key <- read_csv("protocol_key.csv")

list.files("protocols", recursive = TRUE, full.names = FALSE) |> 
  enframe() |> 
  select(clean_protocol_path = value) |>
  left_join(protocol_key, by = "clean_protocol_path") |> 
  select(Folder, Protocol, clean_protocol_path, clean_protocol_url) |> 
  mutate(Protocol = glue::glue("[{Protocol}]({clean_protocol_url})"),
         Protocol = map(Protocol, gt::md)) |>
  identity() -> protocol_tab

protocol_tab |> 
  select(Folder, Protocol) |> 
  mutate(Folder = as.factor(Folder)) |> 
  gt() |> 
  gt::fmt_markdown(Protocol) |> 
  gtExtras::gt_theme_538() |> 
  gt::data_color(
    columns = Folder,
    method = "factor",
    palette = viridis::mako(n = n_distinct(protocol_tab$Folder), alpha = 1),
    domain = NULL,
    reverse = TRUE
  )

```



 <br>

 <br>

 <br>

  