---
title: "University Training"
output:
  distill::distill_article:
    self_contained: false
    anchor_sections: FALSE
    css: [theme_inferno_black.css, background_grad.css]
site: distill::distill_website
#favicon: microscope_white.png
---

```{r, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE, fig.align='center', out.width='90%', fig.retina=2}

knitr::opts_chunk$set(echo = FALSE)

```
  
[Knowledge Link](https://knowledgelink.upenn.edu/) is the source of all general Penn training information. Research coordinators should take CITI Training and REDCap for data analysis. Those looking to take Ben Buys training for creating POs and working with vendors can do so through knowledge link. SAP Concur training is available for those looking to plan travel.  

<details>
<summary style='font-size:1.2rem'> **Knowledge Link** </summary>   
[Knowledge Link](https://knowledgelink.upenn.edu/) is the source of all general Penn training information. Please note not all trainings are necessary for every employee. Annual Penn Profiler assessment will determine your training needs. Speak to your supervisor if you are unsure about any training. HR will also discuss training information and send you automatic updates of required trainings. Some of the Penn-required trainings for new employees:

- Welcome to the Perelman School of Medicine!  
- Protecting Patient Information (HIPAA)  
- Penn Profiler Training Assessment – UNIV  
- Prevention of COVID-19 Transmission In Penn Research Labs-EHRS 
[eLearning] Unconscious Bias for Faculty, Staff, and Students  
- Getting to Penn  
- Safety & Security 
- Penn Medicine Academic Computing Services (PMACS)  
- History & Structure of PSOM 
- Medical Education at PSOM 
- Inclusion & Diversity  
- Perelman School of Medicine New Staff Orientation (For staff)  
- [PennChart Training for Researchers](https://www.med.upenn.edu/ocr/training-and-resources.html) 
- CITI Training - Human Subjects  
</details>


<details>
<summary style='font-size:1.2rem'> **CITI Training** </summary> 
If you are interested in taking the CITI courses, follow the steps on the pdf linked here to set up training for the first time: [Assigning CITI Training PDF](https://acrobat.adobe.com/link/review?uri=urn:aaid:scds:US:21c3fb17-f35f-3fee-8cd4-5da13c3eb365). As you register in the CITI website, the appropriate responses should be: 1) select “Protection of Human Subjects”; 2. say no to the CHOP questions: 3) select “Group 1: Biomedical Research”.  Finally, for GCP, you can say “yes” or “no”.  If you want training beyond the initial, you can take GCP either through CITI or through Penn (they have their our course in Knowledgelink). GCP is required for research coordinators. 

- [UPENN IRB website](https://irb.upenn.edu/) 
- [CITI Training](https://irb.upenn.edu/mission-institutional-review-board-irb/guidance/citi-human-research-protections-training) 
</details>


<details>
<summary style='font-size:1.2rem'> **REDCap** </summary> 
OCR hosts several REDCap training courses which can be found on [Knowledge Link](https://knowledgelink.upenn.edu/). After logging in (using your PennKey and password), search “REDCap” in the “Find Learning” dashboard. Additional trainings (both instructor-led and eLearning) will be added soon. 

[REDCap: Best Practices for Maintaining HIPAA Compliance and Protecting Personal Health Information (PHI)](https://performancemanager4.successfactors.com/saml2/Login?company=71508P&RelayState=/sf/learning?destUrl=https%253a%252f%252fupenn%252eplateau%252ecom%252flearning%252fuser%252fdeeplink%255fredirect%252ejsp%253flinkId%253dONLINE%255fCONTENT%255fSTRUCTURE%2526componentID%253dUP%252e40009%252eITEM%252eREDCAPPHI%2526componentTypeID%253dDOC%2526revisionDate%253d1643722320000%2526fromSF%253dY&company=71508P&_s.crb=wDEu2aCJIIn3VVLPAIkwUpHhv1bLUVLQQxxeE5pybz8%253d) is now required for new users at the time of account creation. The training takes only 5-10 minutes to complete and covers practical ways to make sure any PHI entered into the tool is secure, access is limited, and inappropriate exporting is prevented. You will need to [request access after completion of training](https://redcap.med.upenn.edu/surveys/?s=YbCvd4).

If you have any questions at all, please reach out directly to [psom-ocrops@pobox.upenn.edu](mailto:psom-ocrops@pobox.upenn.edu) or [lauraee@upenn.edu](psom-ocrops@pobox.upenn.edu).  
</details>


<details>
<summary style='font-size:1.2rem'> **PennChart** </summary>  
- [About PennChart](https://www.med.upenn.edu/ocr/about-pennchart2.html)
- [PennChart Training](https://www.med.upenn.edu/ocr/training-and-resources.html)

- If you want View Only EPIC access, at a minimum you should take “PennChart View Only” Training: PennChart Clinical View Only (COURSE HS.20001.ITEM.ISEPCVIEWONLY)   

- If you want full Research Coordinator Access, you will need to take two courses: 
  
    - [PennChart Training for Research Coordinators](https://upenn.plateau.com/learning/user/catalogsearch/catalogSearchDispatchAction.do?searchType=filteredSearch&keywords=PennChart): COURSE UP.40009.ITEM.HSRWS148

    - [PennChart Training for Ambulatory Medical Assistants (MA) and Clinical Research Coordinators (CRC)](https://upenn.plateau.com/learning/user/catalogsearch/catalogSearchDispatchAction.do?searchType=filteredSearch&keywords=PennChart): COURSE HS.20001.ITEM.PCAMBMA  
 
This RC access allows for RCs to create notes in PennChart. If you have a clinical trial monitored by Office of Clinical Research, they require RCs to take the longer series. But for chart abstraction, typically the View Only course is sufficient.  
</details>


<details>
<summary style='font-size:1.2rem'> **SAP Concur & TEM Booking** </summary>  
Used to reimburse travel or event expenses and book travel. Instructor-led demonstration and discussion on Travel & Expense Management at Penn. Demonstration will include Travel Booking as well as creating and submitting an Expense Report.  Discussion topics will include but are not limited to policy, procedure, and practice for travel booking and expense reimbursement for faculty, staff, and students. [Link to Knowledge Link training](https://upenn.plateau.com/learning/user/common/viewItemDetails.do?componentTypeID=COURSE&componentID=UP%2e87022%2eITEM%2eTEM004&revisionDate=1411763520000&fromHistory=true&menuGroup=Learning&menuItem=Learning%20History). 
</details>

<details>
<summary style='font-size:1.2rem'> **BenBuys** </summary>  
BenBuys training hould be taken for any employee looking to order supplies for office or lab. [Link to Knowledge Link Training Sign Up](https://upenn.plateau.com/learning/user/common/viewItemDetails.do?componentTypeID=COURSE&componentID=UP%2e87022%2eITEM%2eBEN006&revisionDate=1349064000000&fromHistory=true&menuGroup=Learning&menuItem=Learning%20History) 

This course is intended for administrative and support staff of the University who will need the ability to submit office or lab orders through the Penn Marketplace, as well as the ability to place custom, service, and special request orders.  

While awaiting training, feel free to shop as a 'Shopper' in the Penn Marketplace. No training is required. Go to: [Shop at the Penn Marketplace](https://cms.business-services.upenn.edu/purchasing/making-purchases/penn-marketplace.html).   

Students have the option of bringing the following course material with them to class:  

- [Requisitioner User Guide](https://benhelps.freshservice.com/a/solutions/articles/15000046328).  

- [Commodity Matrix for approvable purchases](https://benhelps.freshservice.com/support/solutions/articles/15000046132-commodity-matrix) 

- [Object Codes for the Budgets Strings](https://www.finance.upenn.edu/object-codes/) 
</details>


 <br>

 <br>

 <br>
 
